This is a testharness.js-based test.
[FAIL] Bucket quota restricts the size of a file that can be created
  promise_rejects_quotaexceedederror: function "function() { throw e; }" threw object "QuotaExceededError: The operation failed because it would cause the application to exceed its storage quota." that is not a correct QuotaExceededError: property "code" is equal to 0, expected 22
Harness: the test ran to completion.

